site_name: VeniceRCON
repo_name: alliance-apps/VeniceRCON-documentation
repo_url: https://github.com/alliance-apps/VeniceRCON-documentation
theme:
  name: material
  features:
    - instant
plugins:
  - macros
  - search
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - toc:
      permalink: ⚓︎
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - General:
    - Installation: installation/index.md
    - Permissions: scopes/index.md
  - Socket:
    - Instance: socket/instance.md
    - Self: socket/self.md
  - Plugins:
    - Overview: plugin/overview.md
    - Meta: plugin/meta.md
    - Script: plugin/script.md
    - Types:
      - Logger: plugin/types/Logger.md
      - PluginRouter: plugin/types/PluginRouter.md
  - /api:
    - /auth: api/auth.md
  - External Resources:
    - API: /VeniceRCON-documentation/swagger/