site_name: VeniceRCON
repo_name: alliance-apps/VeniceRCON-documentation
repo_url: https://github.com/alliance-apps/VeniceRCON-documentation
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - General:
    - Installation: installation/index.md
    - Permissions: scopes/index.md
  - Socket:
    - Instance: socket/instance.md
    - Self: socket/self.md
  - Plugins:
    - Overview: plugin/overview.md
    - Meta: plugin/meta.md
    - Script: plugin/script.md
    - Types:
      - Logger: plugin/types/Logger.md
      - PluginRouter: plugin/types/PluginRouter.md
  - External Resources:
    - API: /VeniceRCON-documentation/api/