site_name: VeniceRCON
repo_name: alliance-apps/VeniceRCON-documentation
repo_url: https://github.com/alliance-apps/VeniceRCON-documentation
nav:
  - Home: index.md
  - Installation: installation/index.md
  - Socket:
    - Instance: socket/instance.md
    - Self: socket/self.md
  - Scopes: scopes/index.md
  - API: /VeniceRCON-documentation/api/
theme: readthedocs