site_name: VeniceRCON
repo_name: alliance-apps/VeniceRCON-documentation
repo_url: https://github.com/alliance-apps/VeniceRCON-documentation
theme:
  name: material
  features:
    - instant
    - tabs
    - navigation.expand
plugins:
  - macros
  - search
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - toc:
      toc_depth : "1-1"
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - General:
    - Installation: installation/index.md
    - Permissions: scopes/index.md
  - Socket:
    - Instance: socket/instance.md
    - Self: socket/self.md
  - Plugins:
    - Overview: plugin/overview.md
    - Meta: plugin/meta.md
    - Script: plugin/script.md
    - Types:
      - Logger: plugin/types/Logger.md
      - PluginRouter: plugin/types/PluginRouter.md
  - api:
    - api/auth: api/auth.md
    - api/instance: api/instance/index.md
    - api/instance/{instanceId}: api/instance/instance.md
    - api/instance/{instanceId}/users: api/instance/users.md
    - api/instance/{instanceId}/players: api/instance/players.md
    - api/instance/{instanceId}/bans: api/instance/bans.md
    - api/instance/{instanceId}/maps: api/instance/maps.md
    - api/instance/{instanceId}/reservedslot: api/instance/reservedslot.md
    - api/instance/{instanceId}/vars: api/instance/vars.md
    - api/instance/{instanceId}/events: api/instance/events.md
    - api/instance/{instanceId}/plugins: api/instance/plugins.md
    - api/instance/{instanceId}/mods: api/instance/mods.md
    - api/instance/{instanceId}/logs: api/instance/logs.md
extra:
  api:
    schema_path: docs/api/schemas