openapi: 3.0.0
info:
  title: VeniceRCON
  description: API Routes for VeniceRCON
  version: 0.0.1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
tags:
  - name: Auth
    description: routes which handle authentication stuff
  - name: Instance
    description: instance related routes
  - name: InstanceUser
    description: instance related user managment routes
  - name: Player
    description: player managment related routes
  - name: Bans
    description: banning related routes
  - name: Maps
    description: map managment related routes
paths:
  /api/auth/login:
    $ref: "paths/auth/login.yaml"
  /api/auth/whoami:
    $ref: "paths/auth/whoami.yaml"
  /api/auth/invite:
    $ref: "paths/auth/invite.yaml"
  /api/auth/register:
    $ref: "paths/auth/register.yaml"
  /api/instances:
    $ref: "paths/instances/index.yaml"
  /api/instances/{instanceId}:
    $ref: "paths/instances/single/index.yaml"
  /api/instances/{instanceId}/start:
    $ref: "paths/instances/single/start.yaml"
  /api/instances/{instanceId}/stop:
    $ref: "paths/instances/single/stop.yaml"
  /api/instances/{instanceId}/users:
    $ref: "paths/instances/single/users/index.yaml"
  /api/instances/{instanceId}/users/invite:
    $ref: "paths/instances/single/users/invite.yaml"
  /api/instances/{instanceId}/users/{userId}:
    $ref: "paths/instances/single/users/user.yaml"
  /api/instances/{instanceId}/users/{userId}/permissions:
    $ref: "paths/instances/single/users/permissions.yaml"
  /api/instances/{instanceId}/players:
    $ref: "paths/instances/single/players/index.yaml"
  /api/instances/{instanceId}/players/{guid}:
    $ref: "paths/instances/single/players/player.yaml"
  /api/instances/{instanceId}/players/{guid}/kill:
    $ref: "paths/instances/single/players/kill.yaml"
  /api/instances/{instanceId}/players/{guid}/kick:
    $ref: "paths/instances/single/players/kick.yaml"
  /api/instances/{instanceId}/players/{guid}/ban:
    $ref: "paths/instances/single/players/ban.yaml"
  /api/instances/{instanceId}/bans:
    $ref: "paths/instances/single/bans.yaml"
  /api/instances/{instanceId}/maps:
    $ref: "paths/instances/single/maps/index.yaml"
  /api/instances/{instanceId}/maps/current:
    $ref: "paths/instances/single/maps/current.yaml"
  /api/instances/{instanceId}/maps/endRound:
    $ref: "paths/instances/single/maps/endRound.yaml"
  /api/instances/{instanceId}/maps/nextRound:
    $ref: "paths/instances/single/maps/nextRound.yaml"
  /api/instances/{instanceId}/maps/restartRound:
    $ref: "paths/instances/single/maps/restartRound.yaml"
  /api/instances/{instanceId}/maps/{mapIndex}/next:
    $ref: "paths/instances/single/maps/next.yaml"
  /api/instances/{instanceId}/maps/{mapIndex}:
    $ref: "paths/instances/single/maps/map.yaml"