openapi: 3.0.0
info:
  title: VeniceRCON
  description: API Routes for VeniceRCON
  version: 0.0.1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
tags:
  - name: Auth
    description: routes which handle authentication stuff
  - name: Instance
    description: instance related routes
  - name: InstanceUser
    description: instance related user managment routes
  - name: Player
    description: player managment related routes
  - name: Bans
    description: banning related routes
  - name: Maps
    description: map managment related routes
  - name: ReservedSlot
    description: battlefield reserved slot list
  - name: Vars
    description: server variables
paths:
  /api/auth/login:
    $ref: "paths/auth/login.yaml"
  /api/auth/whoami:
    $ref: "paths/auth/whoami.yaml"
  /api/auth/invite:
    $ref: "paths/auth/invite.yaml"
  /api/auth/register:
    $ref: "paths/auth/register.yaml"
  /api/instances:
    $ref: "paths/instances/index.yaml"
  /api/instances/{instanceId}:
    $ref: "paths/instances/instance.yaml"
  /api/instances/{instanceId}/start:
    $ref: "paths/instances/start.yaml"
  /api/instances/{instanceId}/stop:
    $ref: "paths/instances/stop.yaml"
  /api/instances/{instanceId}/message:
    $ref: "paths/instances/message.yaml"
  /api/instances/{instanceId}/users:
    $ref: "paths/instances/users/index.yaml"
  /api/instances/{instanceId}/users/invite:
    $ref: "paths/instances/users/invite.yaml"
  /api/instances/{instanceId}/users/{userId}:
    $ref: "paths/instances/users/user.yaml"
  /api/instances/{instanceId}/users/{userId}/permissions:
    $ref: "paths/instances/users/permissions.yaml"
  /api/instances/{instanceId}/players:
    $ref: "paths/instances/players/index.yaml"
  /api/instances/{instanceId}/players/{guid}:
    $ref: "paths/instances/players/player.yaml"
  /api/instances/{instanceId}/players/{guid}/kill:
    $ref: "paths/instances/players/kill.yaml"
  /api/instances/{instanceId}/players/{guid}/kick:
    $ref: "paths/instances/players/kick.yaml"
  /api/instances/{instanceId}/players/{guid}/ban:
    $ref: "paths/instances/players/ban.yaml"
  /api/instances/{instanceId}/players/{guid}/message:
    $ref: "paths/instances/players/message.yaml"
  /api/instances/{instanceId}/players/{guid}/move:
    $ref: "paths/instances/players/move.yaml"
  /api/instances/{instanceId}/bans:
    $ref: "paths/instances/bans.yaml"
  /api/instances/{instanceId}/maps:
    $ref: "paths/instances/maps/index.yaml"
  /api/instances/{instanceId}/maps/current:
    $ref: "paths/instances/maps/current.yaml"
  /api/instances/{instanceId}/maps/endRound:
    $ref: "paths/instances/maps/endRound.yaml"
  /api/instances/{instanceId}/maps/nextRound:
    $ref: "paths/instances/maps/nextRound.yaml"
  /api/instances/{instanceId}/maps/restartRound:
    $ref: "paths/instances/maps/restartRound.yaml"
  /api/instances/{instanceId}/maps/{mapIndex}/next:
    $ref: "paths/instances/maps/next.yaml"
  /api/instances/{instanceId}/maps/{mapIndex}:
    $ref: "paths/instances/maps/map.yaml"
  /api/instances/{instanceId}/reservedslot:
    $ref: "paths/instances/reservedslot/index.yaml"
  /api/instances/{instanceId}/reservedslot/{slot}:
    $ref: "paths/instances/reservedslot/slot.yaml"
  /api/instances/{instanceId}/vars:
    $ref: "paths/instances/vars/index.yaml"
  /api/instances/{instanceId}/vars/options:
    $ref: "paths/instances/vars/options.yaml"