Plugins:
  type: array
  items:
    $ref: "#/Plugin"
Metas:
  type: array
  items:
    $ref: "#/Meta"
Plugin:
  type: object
  properties:
    id:
      type: number
    storeVersion:
      type: string
    uuid:
      type: string
    store:
      type: string
      nullable: true
    name:
      type: string
    state:
      type: number
      enum: 
        - STOPPED
        - STARTED
    meta:
      $ref: "#/Meta"
    config:
      type: object
Meta:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    version:
      type: string
    author:
      type: string
    backend:
      type: string
    entry:
      type: string
    dependency:
      type: array
      items: 
        type: string
      nullable: true
    vars:
      type: array
      items: 
        $ref: "#/PluginVariables"
StoreItems:
  type: array
  items:
    $ref: "#/StoreItem"
StoreItem:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    version:
      type: string
    author:
      type: string
    type:
      type: string
    uuid:
      type: string
PluginVariables:
  type: object
  properties:
    name: 
      type: string
    description:
      type: string
    type:
      type: string
      enum: 
        - string
        - number
        - boolean
        - strings
        - select
        - array
    multiline?:
      type: boolean
    default:
      type: any
    options:
      type: array
      items:
        type: object
        additionalProperties:
          type: string
    conditions:
      $ref: "#/Conditions"
Conditions:
  type: array
  items:
    $ref: "#/Condition"
Condition:
  type: object
  additionalProperties:
    type: any