name: Swagger

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: apt install
      run: |
        sudo apt install libarchive-tools
    - name: build docs
      run: |
        mkdir tmp
        mkdir build
        cd tmp
        curl -o swagger.zip -L https://github.com/swagger-api/swagger-ui/archive/v3.25.5.zip
        bsdtar -xf swagger.zip -s'|[^/]*/||'
        rm swagger.zip
        sed -i 's/url=".*"/url="swagger\/meta.yaml"/' ./dist/index.html
        cp -R dist/* ../build/
        cp -R ../swagger ../build/
    - name: Deploy on Github Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build